<?php

namespace login\Controllers;


class IndexController extends ControllerBase
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        if($this->auth->getIdentity()){
            $this->dispatcher->forward([
                'controller' => 'record',
                'action' => 'index'
            ]);
        }
    }

}

